[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "noindex, follow"

[[headers]]
  for = "/*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"

[[headers]]
  for = "/*/*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"
